### ISSUE TITLE
`for(;;)` is not handled.

### ISSUE THREAD

**Issue by vi** [Bogdan-Lyashenko/js-code-to-svg-flowchart#1]
```javascript
function q() {
    for(;;) {
    	console.log("dsfsdf"); 
    }
}
```

The diagram on the online demo fails to change unless I add loop condition.

**Comment by Bogdan-Lyashenko** [comment]
Hey, thanks for the nice catch. Fixed and merged. :)
<img width="364" alt="screen shot 2017-11-06 at 21 06 06" src="https://user-images.githubusercontent.com/2098309/32461822-6c2ea518-c337-11e7-909d-36ef7070480d.png">

**Comment by vi** [comment]
The first and the third argument of `for` are also not shown properly. Currently they are just as if they were the statements inside `for{}` block.

Example program:

```js
function test() {
    let q = null;
    for(q=0;q<100;q+=1) {
    	if (q==6) {
         	break; 
        } else {
         	continue; 
        }
    }
}
```

I expect `q=0` to be before the loop and `continue` pointing at `q+=1` (which should be somewhere below) instead just at `for`.

**Comment by Bogdan-Lyashenko** [comment]
Nice, agree. q = 0 definitely should not be on each iteration.
