### ISSUE TITLE
ES6 Destructuring Broken

### ISSUE THREAD

**Issue by molenzwiebel** [Bogdan-Lyashenko/js-code-to-svg-flowchart#11]
As of the current version, array destructuring seems to be broken in some cases.

Works fine:
```js
const [a, b, c] = foo;
```

This renders as
![schermafbeelding 2017-11-15 om 16 30 29](https://user-images.githubusercontent.com/3594254/32844291-52064398-ca22-11e7-9dbb-d571aca0313d.png)

**However**, changing it to the following breaks it:
```js
const [a, b, c] = foo();
```

As you can see, it now renders the lefthand as `undefined`:
![schermafbeelding 2017-11-15 om 16 31 30](https://user-images.githubusercontent.com/3594254/32844357-7486f76e-ca22-11e7-8c25-b9d26c00e314.png)

**Comment by Bogdan-Lyashenko** [comment]
Hey @molenzwiebel, thanks, nice catch. I totally missed ArrayPattern token, added it now 😸  

Fixed, it's gonna look like:
![image](https://user-images.githubusercontent.com/2098309/32856235-7d4aabda-ca44-11e7-817f-8c35c4429d85.png)

similar to ObjectPattern which is done in the same way. Closing issue.
