### ISSUE TITLE
if condition without code block braces

### ISSUE THREAD

**Issue by Jackbennett** [Bogdan-Lyashenko/js-code-to-svg-flowchart#13]
Seems to omit only when using an assignment. Related to #5 ?
# Error:
![image](https://user-images.githubusercontent.com/791134/33025128-f9f7cfaa-ce04-11e7-8b86-8d333501672e.png)

# Expect: 
![image](https://user-images.githubusercontent.com/791134/33025172-212ab88a-ce05-11e7-86c2-0b86d3a46f13.png)

**Comment by Bogdan-Lyashenko** [comment]
@Jackbennett , thanks, you are right, fix #5 was too rough) 

Pused the fix, added more precise condition, covers nicely the code below
```javascript
if ((a=1) || (b=2)) c = 3;
```
![image](https://user-images.githubusercontent.com/2098309/33036640-4d86fd74-ce2f-11e7-8bed-4d3aa8cd3099.png)
