### ISSUE TITLE
Breaks if trying to render a file in a subdirectory.

### ISSUE THREAD

**Issue by almereyda** [Bogdan-Lyashenko/js-code-to-svg-flowchart#18]
For sanity, I tried to keep the custom js2flowchart subfolder, which is a little a pain already, concise by rendering from the root of my project:

```
~/https/github.com/xyz (gh-pages) $ cd scripts 
~/https/github.com/xyz/scripts (gh-pages) $ js2flowchart map.js
SVG file was created: ./js2flowchart/map.js.svg
~/https/github.com/xyz/scripts (gh-pages*) $ cd ..
~/https/github.com/xyz (gh-pages*) $ js2flowchart scripts/map.js
{ Error: ENOENT: no such file or directory, open './js2flowchart/scripts/map.js.svg'
    at Error (native)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './js2flowchart/scripts/map.js.svg' }
```

Apparently this is just not possible, as the script seems to reuse the JS file's path completely for the SVG, including path fragments and not relying on `mkdir -p`-like behaviour.

**Comment by Bogdan-Lyashenko** [comment]
Hi @almereyda, thanks for a good finding. Indeed, I don't like that extra dir as well now 😺 . I've removed it and actually it fixes the issue with subdirectory as well. Pushed the fix, closing the issue.

**Comment by almereyda** [comment]
Many thanks!
