### ISSUE TITLE
For in Failure

### ISSUE THREAD

**Issue by R42O** [Bogdan-Lyashenko/js-code-to-svg-flowchart#19]
`function test () {
  let demo = {'A': 1, 'B': 2}
  for (let key in demo) {
  }
}`

The diagram on the online demo fails to change unless change condition declaration: 

`function test2 () {
  let demo = {'A': 1, 'B': 2}
  let key
  for (key in demo) {
  }
}`

**Comment by Bogdan-Lyashenko** [comment]
@R42O , thanks for the feedback.
Indeed, it was a bug with ```for-in``` loop, and I just pushed the fix for that. But, your snippets above not completely valid (Babel AST builder I use fails there).
Please have a look below: I've added semicolons to make it work.

```function test () { let demo = {'A': 1, 'B': 2}; for (let key in demo) { } }```
and second 
```function test2 () { let demo = {'A': 1, 'B': 2}; let key; for (key in demo) { } }``

<img width="319" alt="screen shot 2017-12-14 at 20 11 49" src="https://user-images.githubusercontent.com/2098309/34009926-176d1b26-e10b-11e7-9e3b-470f2ed562ec.png">

**Comment by R42O** [comment]
Yup sorry idk why code tag didn't respect multiple lines.

And thanks, tomorrow I test it.

**Comment by R42O** [comment]
Okey, its working.

Thanks @Bogdan-Lyashenko
