### ISSUE TITLE
Project support

### ISSUE THREAD

**Issue by Berkmann18** [Bogdan-Lyashenko/js-code-to-svg-flowchart#20]
I've seen that the multi-file support was on the TODO list but as that could mean supporting * ops (e.g: *.js) as well as projects, I was wondering which one it was and if it was the latter, then my question would be:
Will it know about the data-structures that a module (e.g: main.js) uses from another one (regardless of whether it's NodeJS/ES6 modules?
Example in NodeJS (the same could be said for ES6 modules):
main.js
```js
let aModule = require('./aModule');

// some code here
aModule.doSomething();
```

I'm aware that the latter would possibly require a filter to prevent this generator to go deep in the (yarn|node)_modules or any library files that aren't really part of the project so I'm willing to help (if there's need).

**Comment by Bogdan-Lyashenko** [comment]
Hey, thanks for the interest.) well, original idea was to use webpack dependencies tree builder for that, I just can’t imagine another better way of handling modules dependencies, so, the short answer is - webpack will manage that. Nice to hear you would like to contribute, it would be really great, thanks. Let me know if you need some guidance where to start.

**Comment by Berkmann18** [comment]
So would that be basically using webpack without requiring the targeted projects to use webpack?
Sure, will do if I need :).

**Comment by Bogdan-Lyashenko** [comment]
Yes, exactly.)

**Comment by Berkmann18** [comment]
Cool :).
