### ISSUE TITLE
JSX recognition -  is in the plans?

### ISSUE THREAD

**Issue by LucasBadico** [Bogdan-Lyashenko/js-code-to-svg-flowchart#3]
![captura de tela 2017-11-08 as 23 57 10](https://user-images.githubusercontent.com/16516889/32584821-824634c8-c4e1-11e7-9e83-4c97561f01e0.png)
Hey guys, jsx is on the roadmap for the tool? If it is I want to make. Just made a visual studio extension with this, but for really be useful I need the jsx be parsed together with the js.

**Comment by Bogdan-Lyashenko** [comment]
Hey! Yes, JSX in TODOs section, but not sure how soon that gonna happens. I appreciate if you can help with contributing, it’s not complicated and I can help/point you how to get started. AST parser I use here is supposed to work with JSX, so from our side we need:
- map it to FlowTree
- decide how it’s gonna look like and describe SVG for that

**Comment by LucasBadico** [comment]
Nice I could do that. Let me finish the release version of the extension. Then I help you guys with that. Learning now how to ship the extension.

**Comment by LucasBadico** [comment]
Also, add the visual code extensions on your list guys!

**Comment by LucasBadico** [comment]
https://marketplace.visualstudio.com/items?itemName=lucasbadico.code-flowchart
Done!

**Comment by Bogdan-Lyashenko** [comment]
That’s amazing! Great job.

**Comment by Bogdan-Lyashenko** [comment]
You probably can create a pull request with change to Readme, add “Tools” section after “API and examples” and mention your extension there.

**Comment by Bogdan-Lyashenko** [comment]
@LucasBadico , added it by myself, thanks for good tool 👍

**Comment by tsiq-swyx** [comment]
hi i am trying to use this.. i have the extension installed, how do i activate it on my codebase?

**Comment by Bogdan-Lyashenko** [comment]
@tsiq-swyx, just call context menu (right mouse click in source code file) and you should be able to see extra menu item “js to flowchart” there, select it and it should work.

**Comment by tsiq-swyx** [comment]
ah ok. i feel like that should be in the readme lol
