### ISSUE TITLE
Is it possible to make it as a vscode plugin?

### ISSUE THREAD

**Issue by soloproc** [Bogdan-Lyashenko/js-code-to-svg-flowchart#37]

**Comment by Bogdan-Lyashenko** [comment]
There is a plugin for VS already https://marketplace.visualstudio.com/items?itemName=lucasbadico.code-flowchart :)

**Comment by mikeBehar** [comment]
After installing the VS code plugin, I then select "Show JS Flowchart" from the context menu.  Nothing happens.  What am I missing?  

Do I need to add script in html for js2flowchart.js.   I am not using node.js  I use caddy.exe for a local http server,  localhost port 2014

Thanks

**Comment by Bogdan-Lyashenko** [comment]
No, that should work fine. You might ping @LucasBadico, author of the plugin

**Comment by soloproc** [comment]
> There is a plugin for VS already https://marketplace.visualstudio.com/items?itemName=lucasbadico.code-flowchart :)

Thanks

**Comment by soloproc** [comment]
> After installing the VS code plugin, I then select "Show JS Flowchart" from the context menu. Nothing happens. What am I missing?
> 
> Do I need to add script in html for js2flowchart.js. I am not using node.js I use caddy.exe for a local http server, localhost port 2014
> 
> Thanks

I have the same situation,
