### ISSUE TITLE
ES6 parsing issues

### ISSUE THREAD

**Issue by joelnet** [Bogdan-Lyashenko/js-code-to-svg-flowchart#4]
These two code blocks should render the same tree

```javascript
// works as expected
const a = () => {
  return b()
}
```
![image](https://user-images.githubusercontent.com/742630/32673780-319ab0ce-c605-11e7-9ee5-40bc88bde873.png)

```javascript
// does not work as expected
const a = () => b()
```

![image](https://user-images.githubusercontent.com/742630/32673798-487a004c-c605-11e7-80e6-554c7c794ad5.png)

**Comment by Bogdan-Lyashenko** [comment]
Hey, thanks, it's really good description, so was easy to figure out where wrong code logic. 
Fixed:
const a = () => b();
const c = () => { d(); }

<img width="267" alt="screen shot 2017-11-12 at 13 03 47" src="https://user-images.githubusercontent.com/2098309/32699455-704dba48-c7b6-11e7-9a3d-3759464917ef.png">

Actually, babylon parser I use for AST building doesn't handle such lines as 'ReturnStatement', so I needed to add that as 'post-build' modifier to transform all arrow functions.
