### ISSUE TITLE
The demo doesn't work

### ISSUE THREAD

**Issue by wangmeijian** [Bogdan-Lyashenko/js-code-to-svg-flowchart#43]
https://bogdan-lyashenko.github.io/js-code-to-svg-flowchart/docs/live-editor/index.html
The demo doesn't work

**Comment by Bogdan-Lyashenko** [comment]
Hi @wangmeijian, what exactly doesn't work? Do you see this when open that link?
![image](https://user-images.githubusercontent.com/2098309/71716581-9065c100-2e15-11ea-8d17-b84966508f46.png)
What browser do you use?

**Comment by wangmeijian** [comment]
@Bogdan-Lyashenko chrome 79.0.3945.88

**Comment by wangmeijian** [comment]
I use  chrome 79.0.3945.88, I see that,It's not that it can't run. After the demo was loaded, I waited for about 26 seconds before displaying the SVG on the right, which has poor generation performance. My laptop is MacBook Pro 13

**Comment by smesko85** [comment]
> I use chrome 79.0.3945.88, I see that,It's not that it can't run. After the demo was loaded, I waited for about 26 seconds before displaying the SVG on the right, which has poor generation performance. My laptop is MacBook Pro 13

Can you try running in different browser? I've just tested the demo in two different browsers on my mobile phone (Motorola Moto X4), and it works without delay.
As my phone has less processing power than your laptop, I can only assume that your browser runs an extension that is causing the issue, or you are experiencing network issues.

**Comment by wangmeijian** [comment]
@smesko85  After loading and rendering, I refresh the page, there's a cache, it still takes a long time to render, I guess it doesn't have much to do with the web, nor does firefox

**Comment by Berkmann18** [comment]
@wangmeijian I just tried opening the demo on Opera, Chrome, Brave, Firefox and Vivaldi (on a laptop) and it rendered nearly instantly (except on Opera and Chrome which has 1.5+ times the amount of extensions the others have).
So my guess is the same as @smesko85. Try opening the demo in incognito (or where few to no extensions are enabled) and in other browsers to see if it still happens.
If it does, then perhaps your connection might be the issue (assuming you have up-to-date browsers).

**Comment by wangmeijian** [comment]
Maybe. It's really slow to visit github in China
