### ISSUE TITLE
If condition with assignment issue

### ISSUE THREAD

**Issue by robertwhitebit** [Bogdan-Lyashenko/js-code-to-svg-flowchart#5]
The output is wrong when using an assignment in the if condition.

![image](https://user-images.githubusercontent.com/11049034/32689428-a95f6066-c6e4-11e7-9710-5a7ccc98f4ec.png)

![image](https://user-images.githubusercontent.com/11049034/32689488-5578f8e8-c6e6-11e7-880f-336367845613.png)

Great project btw! :heart: it!

**Comment by Bogdan-Lyashenko** [comment]
@robertwhitebit, thanks, good one. Fixed it, 
if (x || (a = 1)) {
        y = 12;
}

<img width="298" alt="screen shot 2017-11-12 at 11 53 02" src="https://user-images.githubusercontent.com/2098309/32698168-ac570a00-c7a0-11e7-8548-d6c8fcbb82b4.png">
 
Added ignore for assignment expression when a parent is condition block (if you are interested).

<img width="847" alt="screen shot 2017-11-12 at 11 59 25" src="https://user-images.githubusercontent.com/2098309/32698178-fc127458-c7a0-11e7-9029-ff14e55abd3d.png">

**Comment by robertwhitebit** [comment]
Wow, that was fast, thanks! :smiley_cat:

**Comment by Bogdan-Lyashenko** [comment]
np)
