### ISSUE TITLE
Flow / jsx parsing support 

### ISSUE THREAD

**Issue by mitermayer** [Bogdan-Lyashenko/js-code-to-svg-flowchart#6]
Thanks for creating this tool, pretty clever! Was wondering if there are plans to support jsx/flow ?

**Comment by Bogdan-Lyashenko** [comment]
@mitermayer, thanks, yep, jsx/flow in TODOs, not sure how soon that's gonna be, so if you can help with contribution it would be awesome.

**Comment by neutraali** [comment]
Note that **Flow** -parsing still fails, for example:

`_image: ?React.Node;` triggers `Error at parseCodeToAST: Unexpected token`.
