### ISSUE TITLE
API for bigger boxes

### ISSUE THREAD

**Issue by jonnitto** [Bogdan-Lyashenko/js-code-to-svg-flowchart#75]
This is a similar issue to #16

We use this for documentation of what some people write in their tools (Similar to Google Tag Manager). Is there a way to allow bigger boxes? The code is always very simple, but the variable names are quite long…

**Comment by Bogdan-Lyashenko** [comment]
Hey, i.e. you would like to change this limit https://github.com/Bogdan-Lyashenko/js-code-to-svg-flowchart/blob/d426751e3da98ae2e19e3962503aa47a0a47e91d/src/render/svg/appearance/TextContentConfigurator.js#L3 ?

**Comment by jonnitto** [comment]
Yes, I think so. But I found no way to do this via API

**Comment by Bogdan-Lyashenko** [comment]
Yeah, it’s not exposed via API indeed. I guess I could fix it (if you really need it, probably on this weekend)

**Comment by jonnitto** [comment]
Wow, this would be awesome!

**Comment by Bogdan-Lyashenko** [comment]
Hey @jonnitto, I just pushed the fix. So essentially that config is part of the `theme` now and to apply it you can do something like
```
svgRender.applyTheme({
    common: {
        maxNameLength: 10
    }
});
```

**Comment by jonnitto** [comment]
Works like a charm! Thank you very much!!
