### ISSUE TITLE
Width problem of multibyte characters 

### ISSUE THREAD

**Issue by azu** [Bogdan-Lyashenko/js-code-to-svg-flowchart#8]
The width of multibyte characters text like emoji, Japanese, Chinese over the width of background shape.

![image](https://user-images.githubusercontent.com/19714/32700091-715f4b2a-c803-11e7-86d3-d400f84340a9.png)

Reproduce code:

```js
while("♥♥♥♥♥♥♥♥♥♥"){
  
}
```

**Comment by Bogdan-Lyashenko** [comment]
@azu , thanks. Well, this one looks pretty tricky. Need to think how to calculate symbol width.. now it goes the same for each symbol, what is not the best solution for the case above.

**Comment by azu** [comment]
Maybe, [string-width](https://github.com/sindresorhus/string-width "string-width") or [wcwidth](https://github.com/timoxley/wcwidth "wcwidth") is helpful.
These provide visual width of string.

**Comment by Bogdan-Lyashenko** [comment]
Hey @azu , thanks, added string-width, looks better now 👍
