### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by cheriansk** [Bogdan-Lyashenko/js-code-to-svg-flowchart#82]
Hi 

Thankyou for this awesome source code and it helped me a lot with my personal projects. When trying to incorporate this with my .net application and deploy on Azure Webapps, due to some of the outdated  dependencies i am getting repeated errors. I tried upgrading the dependencies as below and compilation runs successfully. but the page wont load with below error

--------------------------------------------------------------
Uncaught ReferenceError: process is not defined

index.js:2  Uncaught TypeError: Cannot destructure property 'createFlowTreeBuilder' of 'window.js2flowchart' as it is undefined.
    at index.js:2:5
(anonymous) @ index.js:2

---------------------------------------------------------
Below is the package.json i updated to

{
  "name": "js2flowchart",
  "version": "1.3.4",
  "author": "Bohdan Liashenko",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "https://github.com/Bogdan-Lyashenko/js-code-to-svg-flowchart.git"
  },
  "main": "dist/js2flowchart.js",
  "scripts": {
    "dev": "webpack --progress --colors --watch --env dev",
    "build": "NODE_ENV=production webpack --progress",
    "babel-compile": "babel src -d build --copy-files",
    "pretty": "prettier  --write \"./src/**/*.js\" \"./cli/*.js\""
  },
  "bin": {
    "js2flowchart": "./cli/index.cli.js"
  },
  "devDependencies": {
    "@babel/cli": "^7.22.10",
    "@babel/core": "^7.22.10",
    "@babel/preset-env": "^7.22.10",
    "babel-loader": "^9.1.3",
    "prettier": "3.0.2",
    "webpack": "^5.88.2",
    "webpack-cli": "^5.1.4"
  },
  "keywords": [
    "svg",
    "code analyzeing",
    "webpack",
    "es6",
    "library",
    "universal",
    "umd",
    "commonjs"
  ],
  "dependencies": {
    "@babel/generator": "^7.22.10",
    "@babel/parser": "^7.22.10",
    "@babel/traverse": "^7.22.10",
    "commander": "^11.0.0",
    "deepmerge": "^4.3.1",
    "global": "^4.4.0",
    "string-width": "^6.1.0",
    "uuid": "^9.0.0",
    "xml-escape": "^1.1.0"
  }
}

**Comment by Bogdan-Lyashenko** [comment]
Hey @cheriansk, I upgrated dependencies you mentioned above and published new version (fixed build setup), let me know how it goes. Cheers!

**Comment by cheriansk** [comment]
Wow..thanks a lot @Bogdan-Lyashenko  .. it worked.. seems i missed to update the webpack.config and "buffer": "^6.0.3" in package.json...Still close for a newbie in npm :)

Thanks for the prompt fix and also creating this awesome framework...
